name: Pipeline
on: [push, pull_request]

jobs:
  build-project:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/blackbrad/aoc:2022
      volumes:
        - ${{ github.workspace }}:/aoc
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_GITHUB }}
    steps:
      - uses: actions/checkout@v3
      - run: cd /aoc && make
